MySQL:
  Host: "localhost"
  Port: 3306
  Database: "BuilderTask"
  Username: "root"
  Password: ""


Messages:
  Prefix: '&8[&aBuilderTask&8] &7'
  NoPermission: '&cYou are not allowed to use this command.'
