MySQL:
  Host: "localhost"
  Port: 3306
  Database: "BuilderTask"
  Username: "root"
  Password: ""


Messages:
  Prefix: "&8[&6BuilderTask&8] &7"
  NoPermission: "&cYou are not allowed to use this command."
  PlayerNotOnline: "&cThe selected player is not online."
  SyntaxError: "&cThe syntax is wrong."
  BuilderNoOption: "&cYou have not selected a option."
  BuilderMissingArgument: "&cMissing name of player"
  BuilderCreated: "&aThe builder has successfully been created."
  BuilderCreatedFailure: "&cError while creating the builder."
  BuilderRemoved: "&aThe builder has been removed."
  BuilderRemovedNotExists: "&cThe player is not registered."
  BuilderRemovedFailure: "&cError while removing the builder."
  BuilderDoesNotExists: "&cThe builder is not registered."
  BuilderListHeader: "The current builder list:"
  BuilderListPlayer: "&7-> &e[player]"
  BuilderListError: "&cError while listing player."
  BuilderListNoPlayers: "No Player is registered."
  TaskCreationFailure: "&cError while creating the task."
  TaskDoesNotExists: "&cThe selected task does not exist."
  TaskWorldNotExists: "&cThe selected world does not exist."
  TaskWorldSuccess: "The world has successfully been bound to the task."
  TaskCreationSuccess: "The task has been created with id [id]."
  TaskAssignedSuccess: "The task has been assigned to [player]."
  TaskDeletedSuccess: "The task has been deleted."
  TaskDeletedFailure: "The task could not be deleted."