name: BuilderTask
version: ${project.version}
main: de.prixix.buildertask.BuilderTask
api-version: 1.16
authors: [ Prixix ]
website: https://github.com/Prixix/BuilderTask

commands:
  builder:
  task: