# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Build with Maven (Java 1.8)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build Maven project
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
        with:
          java-version: 1.15
      - name: Setup 2 - Set up JDK 1.15
        uses: actions/setup-java@v1
        with:
            java-version: 1.15
      - name: Step 3 - Build package
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging
      - name: Step 4 - Set up chache for Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: $({ runner.os )}-m2-${( hashFiles('**/pom.xml'))}
          restore-keys: $({ runner.os )}-m2
      - name: Step 5 - Presist workflow data as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: latest-version
          path: staging
